[package]
name = "git-trailers-test"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

publish = false

[lib]
doctest = false
test = true
doc = false

[features]
test = []

[dev-dependencies]
assert_matches = "1.5"
pretty_assertions = "1.1"

[dev-dependencies.git-trailers]
path = ".."
